#!/usr/bin/env bash
# deploy-testnet.sh
#
# Deploys compliance-gate and settlement-escrow to Stellar testnet.
# Outputs contract IDs and writes them to orchestrator/.env.testnet
#
# Usage:
#   ./scripts/deploy-testnet.sh [--account <key-name>]
#
# Prerequisites:
#   - stellar CLI v27+ installed (https://github.com/stellar/stellar-cli/releases)
#   - Rust toolchain with wasm32v1-none target:
#       rustup target add wasm32v1-none
#
# On first run the script generates and funds a deployer key automatically.
# Pass --account <name> to reuse an existing key (stellar keys ls).

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────

NETWORK="testnet"
NETWORK_RPC="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
ACCOUNT="${2:-atomic-settle-deployer}"  # default key name; override with --account
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ESCROW_DIR="$REPO_ROOT/contracts/settlement-escrow"
GATE_DIR="$REPO_ROOT/contracts/compliance-gate"
ESCROW_WASM="$ESCROW_DIR/target/wasm32v1-none/release/settlement_escrow.wasm"
GATE_WASM="$GATE_DIR/target/wasm32v1-none/release/compliance_gate.wasm"
ENV_OUT="$REPO_ROOT/orchestrator/.env.testnet"

# ── Parse args ───────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case $1 in
    --account) ACCOUNT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

echo "======================================================================"
echo "  atomic-settle testnet deployment"
echo "  network  : $NETWORK"
echo "  rpc url  : $NETWORK_RPC"
echo "  account  : $ACCOUNT"
echo "======================================================================"

# ── Check stellar CLI ─────────────────────────────────────────────────────

if ! command -v stellar &>/dev/null; then
  echo "ERROR: stellar CLI not found."
  echo "Install: https://github.com/stellar/stellar-cli/releases/tag/v27.0.0"
  exit 1
fi
echo "stellar CLI: $(stellar version | head -1)"

# ── Add testnet network config ────────────────────────────────────────────

echo ""
echo "→ Configuring testnet network..."
stellar network add "$NETWORK" \
  --rpc-url "$NETWORK_RPC" \
  --network-passphrase "$NETWORK_PASSPHRASE" 2>/dev/null || true

# ── Generate / fund deployer key ──────────────────────────────────────────

echo ""
echo "→ Setting up deployer account..."
if stellar keys show "$ACCOUNT" &>/dev/null; then
  echo "  Key '$ACCOUNT' already exists — reusing."
else
  echo "  Generating new key '$ACCOUNT'..."
  stellar keys generate "$ACCOUNT" --network "$NETWORK" --fund
  echo "  Funded via friendbot."
fi

DEPLOYER_ADDRESS=$(stellar keys address "$ACCOUNT")
echo "  Deployer address: $DEPLOYER_ADDRESS"

# ── Build contracts ───────────────────────────────────────────────────────

echo ""
echo "→ Building contracts (wasm32v1-none)..."

# Ensure the ed25519-dalek pin is applied before building
(
  cd "$GATE_DIR"
  if cargo tree -p ed25519-dalek 2>/dev/null | grep -q "3\.0\.0"; then
    echo "  Pinning ed25519-dalek@3.0.0 → 2.2.0 in compliance-gate..."
    cargo update "ed25519-dalek@3.0.0" --precise 2.2.0
  fi
  cargo build --target wasm32v1-none --release --quiet
)
echo "  compliance-gate   built ✓  ($(du -sh "$GATE_WASM" | cut -f1))"

(
  cd "$ESCROW_DIR"
  if cargo tree -p ed25519-dalek 2>/dev/null | grep -q "3\.0\.0"; then
    echo "  Pinning ed25519-dalek@3.0.0 → 2.2.0 in settlement-escrow..."
    cargo update "ed25519-dalek@3.0.0" --precise 2.2.0
  fi
  cargo build --target wasm32v1-none --release --quiet
)
echo "  settlement-escrow built ✓  ($(du -sh "$ESCROW_WASM" | cut -f1))"

# ── Deploy compliance-gate ────────────────────────────────────────────────

echo ""
echo "→ Deploying compliance-gate..."
# compliance-gate has a __constructor that requires an admin address
GATE_CONTRACT_ID=$(stellar contract deploy \
  --wasm "$GATE_WASM" \
  --source "$ACCOUNT" \
  --network "$NETWORK" \
  -- \
  --admin "$DEPLOYER_ADDRESS")

echo "  compliance-gate contract ID : $GATE_CONTRACT_ID"

# ── Deploy settlement-escrow ──────────────────────────────────────────────

echo ""
echo "→ Deploying settlement-escrow..."
ESCROW_CONTRACT_ID=$(stellar contract deploy \
  --wasm "$ESCROW_WASM" \
  --source "$ACCOUNT" \
  --network "$NETWORK")

echo "  settlement-escrow contract ID: $ESCROW_CONTRACT_ID"

# ── Write .env.testnet ────────────────────────────────────────────────────

echo ""
echo "→ Writing $ENV_OUT..."
cat > "$ENV_OUT" <<EOF
# Generated by scripts/deploy-testnet.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Stellar Testnet — DO NOT use on mainnet

SOROBAN_RPC_URL=$NETWORK_RPC
SOROBAN_NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
SETTLEMENT_ESCROW_CONTRACT_ID=$ESCROW_CONTRACT_ID
COMPLIANCE_GATE_CONTRACT_ID=$GATE_CONTRACT_ID
DEPLOYER_ADDRESS=$DEPLOYER_ADDRESS
EVENT_LISTENER_ENABLED=true
EVENT_POLL_INTERVAL_MS=5000

# Database (update with your own connection string)
DATABASE_URL=postgresql://localhost:5432/atomic_settle_testnet
EOF

# ── Summary ───────────────────────────────────────────────────────────────

echo ""
echo "======================================================================"
echo "  DEPLOYMENT COMPLETE"
echo "======================================================================"
echo ""
echo "  compliance-gate   : $GATE_CONTRACT_ID"
echo "  settlement-escrow : $ESCROW_CONTRACT_ID"
echo "  deployer          : $DEPLOYER_ADDRESS"
echo ""
echo "  Explorer links:"
echo "  https://stellar.expert/explorer/testnet/contract/$GATE_CONTRACT_ID"
echo "  https://stellar.expert/explorer/testnet/contract/$ESCROW_CONTRACT_ID"
echo ""
echo "  Env file written to: $ENV_OUT"
echo "  Copy to orchestrator/.env to use:  cp $ENV_OUT $REPO_ROOT/orchestrator/.env"
echo ""
echo "  Next steps:"
echo "  1. cd orchestrator && cp ../.env.testnet .env"
echo "  2. npm install && npm run start:dev"
echo "  3. POST /trades to create a trade, referencing the contract IDs above"
echo "======================================================================"
